joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 0
      y: 1
    scale_linear:
      x: 1.0
      y: 1.0
    
    axis_angular:
      yaw: 4
    scale_angular:
    # radians per second
      yaw: 1.0
    
    enable_button: 9 # this is a deadman's switch

    require_enable_button: true # true by default