; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:WvSh_Matrix_esp32s3]
platform = espressif32 @ 6.11.0
board = esp32-s3-devkitm-1
board_build.flash_size = 4MB
board_build.partitions = partitions/max_app_4MB.csv
board_upload.flash_size = 4MB
; end of board settings
framework = arduino
monitor_speed = 115200
board_microros_distro = humble
board_microros_transport = wifi
build_flags = 
    -D MICRO_ROS_AGENT_IP="192.168.1.210"
    -D MICRO_ROS_AGENT_PORT=8888
    -D WIFI_SSID="FBISurveillanceVan#23"
    -D WIFI_PASSWORD="m@xsT0pT0uchingTh@T"
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; allows the Matrix board to send serial output
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    Motoron